// This file is automatically generated by qtc from "repo.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line repo.qtpl:1
package template

//line repo.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line repo.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line repo.qtpl:1
func StreamRepository(qw422016 *qt422016.Writer, owner, repo, description, avatarURL, thisURL, badgeURL string) {
	//line repo.qtpl:1
	qw422016.N().S(`
<!DOCTYPE HTML>
<html>

<head>
  <title>`)
	//line repo.qtpl:6
	qw422016.E().S(owner)
	//line repo.qtpl:6
	qw422016.N().S(`/`)
	//line repo.qtpl:6
	qw422016.E().S(repo)
	//line repo.qtpl:6
	qw422016.N().S(` - GradleUpdate</title>
  <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/cosmo/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-h21C2fcDk/eFsW9sC9h0dhokq5pDinLNklTKoxIZRUn3+hvmgQSffLLQ4G4l2eEr"
        crossorigin="anonymous"/>
  <link href="/static/app.css" rel="stylesheet"/>
</head>
<body>

<div class="container">
	<section class="text-center">
		<div class="jumbotron">
      <img src="`)
	//line repo.qtpl:18
	qw422016.E().S(avatarURL)
	//line repo.qtpl:18
	qw422016.N().S(`" alt="avatar" width="160" height="160" class="img-circle"/>
      <h2>`)
	//line repo.qtpl:19
	qw422016.E().S(description)
	//line repo.qtpl:19
	qw422016.N().S(`</h2>
      <p>`)
	//line repo.qtpl:20
	qw422016.E().S(owner)
	//line repo.qtpl:20
	qw422016.N().S(`/`)
	//line repo.qtpl:20
	qw422016.E().S(repo)
	//line repo.qtpl:20
	qw422016.N().S(`</p>
      <p>
        <img src="/`)
	//line repo.qtpl:22
	qw422016.E().S(owner)
	//line repo.qtpl:22
	qw422016.N().S(`/`)
	//line repo.qtpl:22
	qw422016.E().S(repo)
	//line repo.qtpl:22
	qw422016.N().S(`/status.svg" alt="badge"/>
      </p>
      <form>
        <label class="text-uppercase" for="badge-markdown">Markdown:</label>
        <input type="text" id="badge-markdown" class="form-control input-text-monospace"
          value="[![Gradle Status](`)
	//line repo.qtpl:27
	qw422016.E().S(badgeURL)
	//line repo.qtpl:27
	qw422016.N().S(`)](`)
	//line repo.qtpl:27
	qw422016.E().S(thisURL)
	//line repo.qtpl:27
	qw422016.N().S(`)"/>
      </form>
    </div>
	</section>
</div>

<section id="footer">
	<p>GradleUpdate &copy; Hidetake Iwata</p>
</section>

</body>
</html>
`)
//line repo.qtpl:39
}

//line repo.qtpl:39
func WriteRepository(qq422016 qtio422016.Writer, owner, repo, description, avatarURL, thisURL, badgeURL string) {
	//line repo.qtpl:39
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line repo.qtpl:39
	StreamRepository(qw422016, owner, repo, description, avatarURL, thisURL, badgeURL)
	//line repo.qtpl:39
	qt422016.ReleaseWriter(qw422016)
//line repo.qtpl:39
}

//line repo.qtpl:39
func Repository(owner, repo, description, avatarURL, thisURL, badgeURL string) string {
	//line repo.qtpl:39
	qb422016 := qt422016.AcquireByteBuffer()
	//line repo.qtpl:39
	WriteRepository(qb422016, owner, repo, description, avatarURL, thisURL, badgeURL)
	//line repo.qtpl:39
	qs422016 := string(qb422016.B)
	//line repo.qtpl:39
	qt422016.ReleaseByteBuffer(qb422016)
	//line repo.qtpl:39
	return qs422016
//line repo.qtpl:39
}
