// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/int128/gradleupdate/gateways/interfaces (interfaces: BadgeLastAccessRepository)

// Package mock_gateways is a generated GoMock package.
package mock_gateways

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	domain "github.com/int128/gradleupdate/domain"
	reflect "reflect"
	time "time"
)

// MockBadgeLastAccessRepository is a mock of BadgeLastAccessRepository interface
type MockBadgeLastAccessRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBadgeLastAccessRepositoryMockRecorder
}

// MockBadgeLastAccessRepositoryMockRecorder is the mock recorder for MockBadgeLastAccessRepository
type MockBadgeLastAccessRepositoryMockRecorder struct {
	mock *MockBadgeLastAccessRepository
}

// NewMockBadgeLastAccessRepository creates a new mock instance
func NewMockBadgeLastAccessRepository(ctrl *gomock.Controller) *MockBadgeLastAccessRepository {
	mock := &MockBadgeLastAccessRepository{ctrl: ctrl}
	mock.recorder = &MockBadgeLastAccessRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockBadgeLastAccessRepository) EXPECT() *MockBadgeLastAccessRepositoryMockRecorder {
	return m.recorder
}

// FindBySince mocks base method
func (m *MockBadgeLastAccessRepository) FindBySince(arg0 context.Context, arg1 time.Time) ([]domain.BadgeLastAccess, error) {
	ret := m.ctrl.Call(m, "FindBySince", arg0, arg1)
	ret0, _ := ret[0].([]domain.BadgeLastAccess)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySince indicates an expected call of FindBySince
func (mr *MockBadgeLastAccessRepositoryMockRecorder) FindBySince(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySince", reflect.TypeOf((*MockBadgeLastAccessRepository)(nil).FindBySince), arg0, arg1)
}

// Save mocks base method
func (m *MockBadgeLastAccessRepository) Save(arg0 context.Context, arg1 domain.BadgeLastAccess) error {
	ret := m.ctrl.Call(m, "Save", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save
func (mr *MockBadgeLastAccessRepositoryMockRecorder) Save(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockBadgeLastAccessRepository)(nil).Save), arg0, arg1)
}
