// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/int128/gradleupdate/gateways/interfaces (interfaces: BadgeLastAccessRepository)

// Package mock_gateways is a generated GoMock package.
package mock_gateways

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	domain "github.com/int128/gradleupdate/domain"
	reflect "reflect"
)

// MockBadgeLastAccessRepository is a mock of BadgeLastAccessRepository interface
type MockBadgeLastAccessRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBadgeLastAccessRepositoryMockRecorder
}

// MockBadgeLastAccessRepositoryMockRecorder is the mock recorder for MockBadgeLastAccessRepository
type MockBadgeLastAccessRepositoryMockRecorder struct {
	mock *MockBadgeLastAccessRepository
}

// NewMockBadgeLastAccessRepository creates a new mock instance
func NewMockBadgeLastAccessRepository(ctrl *gomock.Controller) *MockBadgeLastAccessRepository {
	mock := &MockBadgeLastAccessRepository{ctrl: ctrl}
	mock.recorder = &MockBadgeLastAccessRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockBadgeLastAccessRepository) EXPECT() *MockBadgeLastAccessRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method
func (m *MockBadgeLastAccessRepository) Get(arg0 context.Context, arg1 domain.RepositoryID) (*domain.BadgeLastAccess, error) {
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*domain.BadgeLastAccess)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockBadgeLastAccessRepositoryMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockBadgeLastAccessRepository)(nil).Get), arg0, arg1)
}

// Put mocks base method
func (m *MockBadgeLastAccessRepository) Put(arg0 context.Context, arg1 domain.BadgeLastAccess) error {
	ret := m.ctrl.Call(m, "Put", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put
func (mr *MockBadgeLastAccessRepositoryMockRecorder) Put(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockBadgeLastAccessRepository)(nil).Put), arg0, arg1)
}
