// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/int128/gradleupdate/gateways/interfaces (interfaces: GradleService)

// Package mock_gateways is a generated GoMock package.
package mock_gateways

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	domain "github.com/int128/gradleupdate/domain"
	reflect "reflect"
)

// MockGradleService is a mock of GradleService interface
type MockGradleService struct {
	ctrl     *gomock.Controller
	recorder *MockGradleServiceMockRecorder
}

// MockGradleServiceMockRecorder is the mock recorder for MockGradleService
type MockGradleServiceMockRecorder struct {
	mock *MockGradleService
}

// NewMockGradleService creates a new mock instance
func NewMockGradleService(ctrl *gomock.Controller) *MockGradleService {
	mock := &MockGradleService{ctrl: ctrl}
	mock.recorder = &MockGradleServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockGradleService) EXPECT() *MockGradleServiceMockRecorder {
	return m.recorder
}

// GetCurrentVersion mocks base method
func (m *MockGradleService) GetCurrentVersion(arg0 context.Context) (domain.GradleVersion, error) {
	ret := m.ctrl.Call(m, "GetCurrentVersion", arg0)
	ret0, _ := ret[0].(domain.GradleVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentVersion indicates an expected call of GetCurrentVersion
func (mr *MockGradleServiceMockRecorder) GetCurrentVersion(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentVersion", reflect.TypeOf((*MockGradleService)(nil).GetCurrentVersion), arg0)
}
