steps:
  - name: gcr.io/cloud-builders/gcloud
    env:
      - TAG_NAME=$TAG_NAME
    entrypoint: bash
    args:
      - -c
      - |
        gcloud app deploy app.yaml queue.yaml cron.yaml --version="${TAG_NAME//./-}"

timeout: "600s"
