steps:
  - name: gcr.io/cloud-builders/gcloud
    env:
      - TAG_NAME=$TAG_NAME
    entrypoint: bash
    args:
      - -c
      - |
        gcloud app deploy --version="${TAG_NAME//./-}";
        gcloud app deploy queue.yaml;

timeout: "600s"
