// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/int128/gradleupdate/usecases/interfaces (interfaces: GetBadge,GetRepository,SendUpdate,BatchSendUpdates,SendPullRequest)

// Package usecasesTestDoubles is a generated GoMock package.
package usecasesTestDoubles

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	git "github.com/int128/gradleupdate/domain/git"
	gradleupdate "github.com/int128/gradleupdate/domain/gradleupdate"
	interfaces "github.com/int128/gradleupdate/usecases/interfaces"
	reflect "reflect"
)

// MockGetBadge is a mock of GetBadge interface
type MockGetBadge struct {
	ctrl     *gomock.Controller
	recorder *MockGetBadgeMockRecorder
}

// MockGetBadgeMockRecorder is the mock recorder for MockGetBadge
type MockGetBadgeMockRecorder struct {
	mock *MockGetBadge
}

// NewMockGetBadge creates a new mock instance
func NewMockGetBadge(ctrl *gomock.Controller) *MockGetBadge {
	mock := &MockGetBadge{ctrl: ctrl}
	mock.recorder = &MockGetBadgeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockGetBadge) EXPECT() *MockGetBadgeMockRecorder {
	return m.recorder
}

// Do mocks base method
func (m *MockGetBadge) Do(arg0 context.Context, arg1 git.RepositoryID) (*interfaces.GetBadgeResponse, error) {
	ret := m.ctrl.Call(m, "Do", arg0, arg1)
	ret0, _ := ret[0].(*interfaces.GetBadgeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do
func (mr *MockGetBadgeMockRecorder) Do(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockGetBadge)(nil).Do), arg0, arg1)
}

// IsNoGradleVersionError mocks base method
func (m *MockGetBadge) IsNoGradleVersionError(arg0 error) bool {
	ret := m.ctrl.Call(m, "IsNoGradleVersionError", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsNoGradleVersionError indicates an expected call of IsNoGradleVersionError
func (mr *MockGetBadgeMockRecorder) IsNoGradleVersionError(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsNoGradleVersionError", reflect.TypeOf((*MockGetBadge)(nil).IsNoGradleVersionError), arg0)
}

// MockGetRepository is a mock of GetRepository interface
type MockGetRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGetRepositoryMockRecorder
}

// MockGetRepositoryMockRecorder is the mock recorder for MockGetRepository
type MockGetRepositoryMockRecorder struct {
	mock *MockGetRepository
}

// NewMockGetRepository creates a new mock instance
func NewMockGetRepository(ctrl *gomock.Controller) *MockGetRepository {
	mock := &MockGetRepository{ctrl: ctrl}
	mock.recorder = &MockGetRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockGetRepository) EXPECT() *MockGetRepositoryMockRecorder {
	return m.recorder
}

// Do mocks base method
func (m *MockGetRepository) Do(arg0 context.Context, arg1 git.RepositoryID) (*interfaces.GetRepositoryResponse, error) {
	ret := m.ctrl.Call(m, "Do", arg0, arg1)
	ret0, _ := ret[0].(*interfaces.GetRepositoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do
func (mr *MockGetRepositoryMockRecorder) Do(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockGetRepository)(nil).Do), arg0, arg1)
}

// IsNoSuchRepositoryError mocks base method
func (m *MockGetRepository) IsNoSuchRepositoryError(arg0 error) bool {
	ret := m.ctrl.Call(m, "IsNoSuchRepositoryError", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsNoSuchRepositoryError indicates an expected call of IsNoSuchRepositoryError
func (mr *MockGetRepositoryMockRecorder) IsNoSuchRepositoryError(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsNoSuchRepositoryError", reflect.TypeOf((*MockGetRepository)(nil).IsNoSuchRepositoryError), arg0)
}

// MockSendUpdate is a mock of SendUpdate interface
type MockSendUpdate struct {
	ctrl     *gomock.Controller
	recorder *MockSendUpdateMockRecorder
}

// MockSendUpdateMockRecorder is the mock recorder for MockSendUpdate
type MockSendUpdateMockRecorder struct {
	mock *MockSendUpdate
}

// NewMockSendUpdate creates a new mock instance
func NewMockSendUpdate(ctrl *gomock.Controller) *MockSendUpdate {
	mock := &MockSendUpdate{ctrl: ctrl}
	mock.recorder = &MockSendUpdateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSendUpdate) EXPECT() *MockSendUpdateMockRecorder {
	return m.recorder
}

// Do mocks base method
func (m *MockSendUpdate) Do(arg0 context.Context, arg1 git.RepositoryID) error {
	ret := m.ctrl.Call(m, "Do", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Do indicates an expected call of Do
func (mr *MockSendUpdateMockRecorder) Do(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockSendUpdate)(nil).Do), arg0, arg1)
}

// HasPreconditionViolation mocks base method
func (m *MockSendUpdate) HasPreconditionViolation(arg0 error) gradleupdate.PreconditionViolation {
	ret := m.ctrl.Call(m, "HasPreconditionViolation", arg0)
	ret0, _ := ret[0].(gradleupdate.PreconditionViolation)
	return ret0
}

// HasPreconditionViolation indicates an expected call of HasPreconditionViolation
func (mr *MockSendUpdateMockRecorder) HasPreconditionViolation(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasPreconditionViolation", reflect.TypeOf((*MockSendUpdate)(nil).HasPreconditionViolation), arg0)
}

// IsNoSuchRepositoryError mocks base method
func (m *MockSendUpdate) IsNoSuchRepositoryError(arg0 error) bool {
	ret := m.ctrl.Call(m, "IsNoSuchRepositoryError", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsNoSuchRepositoryError indicates an expected call of IsNoSuchRepositoryError
func (mr *MockSendUpdateMockRecorder) IsNoSuchRepositoryError(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsNoSuchRepositoryError", reflect.TypeOf((*MockSendUpdate)(nil).IsNoSuchRepositoryError), arg0)
}

// MockBatchSendUpdates is a mock of BatchSendUpdates interface
type MockBatchSendUpdates struct {
	ctrl     *gomock.Controller
	recorder *MockBatchSendUpdatesMockRecorder
}

// MockBatchSendUpdatesMockRecorder is the mock recorder for MockBatchSendUpdates
type MockBatchSendUpdatesMockRecorder struct {
	mock *MockBatchSendUpdates
}

// NewMockBatchSendUpdates creates a new mock instance
func NewMockBatchSendUpdates(ctrl *gomock.Controller) *MockBatchSendUpdates {
	mock := &MockBatchSendUpdates{ctrl: ctrl}
	mock.recorder = &MockBatchSendUpdatesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockBatchSendUpdates) EXPECT() *MockBatchSendUpdatesMockRecorder {
	return m.recorder
}

// Do mocks base method
func (m *MockBatchSendUpdates) Do(arg0 context.Context) error {
	ret := m.ctrl.Call(m, "Do", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Do indicates an expected call of Do
func (mr *MockBatchSendUpdatesMockRecorder) Do(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockBatchSendUpdates)(nil).Do), arg0)
}

// MockSendPullRequest is a mock of SendPullRequest interface
type MockSendPullRequest struct {
	ctrl     *gomock.Controller
	recorder *MockSendPullRequestMockRecorder
}

// MockSendPullRequestMockRecorder is the mock recorder for MockSendPullRequest
type MockSendPullRequestMockRecorder struct {
	mock *MockSendPullRequest
}

// NewMockSendPullRequest creates a new mock instance
func NewMockSendPullRequest(ctrl *gomock.Controller) *MockSendPullRequest {
	mock := &MockSendPullRequest{ctrl: ctrl}
	mock.recorder = &MockSendPullRequestMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSendPullRequest) EXPECT() *MockSendPullRequestMockRecorder {
	return m.recorder
}

// Do mocks base method
func (m *MockSendPullRequest) Do(arg0 context.Context, arg1 interfaces.SendPullRequestRequest) error {
	ret := m.ctrl.Call(m, "Do", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Do indicates an expected call of Do
func (mr *MockSendPullRequestMockRecorder) Do(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockSendPullRequest)(nil).Do), arg0, arg1)
}
