// This file is automatically generated by qtc from "errors.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line errors.qtpl:1
package templates

//line errors.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line errors.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line errors.qtpl:1
func StreamNotFoundError(qw422016 *qt422016.Writer, message string) {
	//line errors.qtpl:1
	qw422016.N().S(`
<!DOCTYPE HTML>
<html>
<head>
  <title>Not Found - gradleupdate</title>
  `)
	//line errors.qtpl:6
	StreamStylesheets(qw422016)
	//line errors.qtpl:6
	qw422016.N().S(`
</head>
<body>
`)
	//line errors.qtpl:9
	StreamHeader(qw422016)
	//line errors.qtpl:9
	qw422016.N().S(`
<div class="container jumbotron text-center">
  <h2>Not Found</h2>
  <p class="lead">`)
	//line errors.qtpl:12
	qw422016.E().S(message)
	//line errors.qtpl:12
	qw422016.N().S(`</p>
</div>
`)
	//line errors.qtpl:14
	StreamFooter(qw422016)
	//line errors.qtpl:14
	qw422016.N().S(`
</body>
</html>
`)
//line errors.qtpl:17
}

//line errors.qtpl:17
func WriteNotFoundError(qq422016 qtio422016.Writer, message string) {
	//line errors.qtpl:17
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line errors.qtpl:17
	StreamNotFoundError(qw422016, message)
	//line errors.qtpl:17
	qt422016.ReleaseWriter(qw422016)
//line errors.qtpl:17
}

//line errors.qtpl:17
func NotFoundError(message string) string {
	//line errors.qtpl:17
	qb422016 := qt422016.AcquireByteBuffer()
	//line errors.qtpl:17
	WriteNotFoundError(qb422016, message)
	//line errors.qtpl:17
	qs422016 := string(qb422016.B)
	//line errors.qtpl:17
	qt422016.ReleaseByteBuffer(qb422016)
	//line errors.qtpl:17
	return qs422016
//line errors.qtpl:17
}

//line errors.qtpl:19
func StreamServerError(qw422016 *qt422016.Writer) {
	//line errors.qtpl:19
	qw422016.N().S(`
<!DOCTYPE HTML>
<html>
<head>
  <title>gradleupdate</title>
  `)
	//line errors.qtpl:24
	StreamStylesheets(qw422016)
	//line errors.qtpl:24
	qw422016.N().S(`
</head>
<body>
`)
	//line errors.qtpl:27
	StreamHeader(qw422016)
	//line errors.qtpl:27
	qw422016.N().S(`
<div class="container jumbotron text-center">
  <h2>Oops!</h2>
  <p class="lead">Something wrong</p>
</div>
`)
	//line errors.qtpl:32
	StreamFooter(qw422016)
	//line errors.qtpl:32
	qw422016.N().S(`
</body>
</html>
`)
//line errors.qtpl:35
}

//line errors.qtpl:35
func WriteServerError(qq422016 qtio422016.Writer) {
	//line errors.qtpl:35
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line errors.qtpl:35
	StreamServerError(qw422016)
	//line errors.qtpl:35
	qt422016.ReleaseWriter(qw422016)
//line errors.qtpl:35
}

//line errors.qtpl:35
func ServerError() string {
	//line errors.qtpl:35
	qb422016 := qt422016.AcquireByteBuffer()
	//line errors.qtpl:35
	WriteServerError(qb422016)
	//line errors.qtpl:35
	qs422016 := string(qb422016.B)
	//line errors.qtpl:35
	qt422016.ReleaseByteBuffer(qb422016)
	//line errors.qtpl:35
	return qs422016
//line errors.qtpl:35
}
