// This file is automatically generated by qtc from "index.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line index.qtpl:1
package templates

//line index.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line index.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line index.qtpl:1
func StreamIndex(qw422016 *qt422016.Writer, csrf string) {
	//line index.qtpl:1
	qw422016.N().S(`
<!DOCTYPE HTML>
<html>

<head>
  <title>gradleupdate</title>
  <meta name="description"
        content="gradleupdate provides continuous update of Gradle Wrapper in your GitHub repositories"/>
  `)
	//line index.qtpl:9
	StreamStylesheets(qw422016)
	//line index.qtpl:9
	qw422016.N().S(`
</head>
<body>

<div class="container jumbotron text-center">
  <h1>gradleupdate</h1>
  <p class="lead">Automatic Gradle Update Service</p>
  <p>
    <img src="/int128/latest-gradle-wrapper/status.svg"/>
  </p>
</div>

<div class="container text-center">
  <form method="post" action="/landing">
    <div class="form-group">
      <label for="github-url">Paste GitHub URL</label>
      <input type="text" id="github-url" name="url"
             class="form-control text-center input-lg text-monospace"
             placeholder="https://github.com/int128/gradleupdate"/>
      `)
	//line index.qtpl:28
	qw422016.N().S(csrf)
	//line index.qtpl:28
	qw422016.N().S(`
    </div>
    <button type="submit" class="btn btn-primary">Get your Badge</button>
  </form>
</div>

`)
	//line index.qtpl:34
	StreamFooter(qw422016)
	//line index.qtpl:34
	qw422016.N().S(`

</body>
</html>
`)
//line index.qtpl:38
}

//line index.qtpl:38
func WriteIndex(qq422016 qtio422016.Writer, csrf string) {
	//line index.qtpl:38
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line index.qtpl:38
	StreamIndex(qw422016, csrf)
	//line index.qtpl:38
	qt422016.ReleaseWriter(qw422016)
//line index.qtpl:38
}

//line index.qtpl:38
func Index(csrf string) string {
	//line index.qtpl:38
	qb422016 := qt422016.AcquireByteBuffer()
	//line index.qtpl:38
	WriteIndex(qb422016, csrf)
	//line index.qtpl:38
	qs422016 := string(qb422016.B)
	//line index.qtpl:38
	qt422016.ReleaseByteBuffer(qb422016)
	//line index.qtpl:38
	return qs422016
//line index.qtpl:38
}
