// This file is automatically generated by qtc from "index.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line index.qtpl:1
package templates

//line index.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line index.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line index.qtpl:1
func StreamIndex(qw422016 *qt422016.Writer) {
	//line index.qtpl:1
	qw422016.N().S(`
<!DOCTYPE HTML>
<html>

<head>
  <title>gradleupdate</title>
  <meta name="description"
        content="gradleupdate provides continuous update of Gradle Wrapper in your GitHub repositories"/>
  `)
	//line index.qtpl:9
	StreamStylesheets(qw422016)
	//line index.qtpl:9
	qw422016.N().S(`
</head>
<body>

`)
	//line index.qtpl:13
	StreamHeader(qw422016)
	//line index.qtpl:13
	qw422016.N().S(`

<div class="container">
  <section class="text-center">
    <div class="jumbotron">
      <h1>gradleupdate</h1>
      <p>Automatic Gradle Update Service</p>
      <p>
        <img src="/int128/latest-gradle-wrapper/status.svg"/>
      </p>
    </div>
  </section>
  <section class="text-center">
    <form method="post" action="/landing">
      <div class="form-group">
        <label for="github-url">
          Paste GitHub URL
        </label>
        <input type="text" id="github-url" name="url"
               class="form-control text-center input-lg input-text-monospace"
               placeholder="https://github.com/int128/gradleupdate"/>
      </div>
      <button type="submit" class="btn btn-primary">Get your Badge</button>
    </form>
  </section>
</div>

`)
	//line index.qtpl:40
	StreamFooter(qw422016)
	//line index.qtpl:40
	qw422016.N().S(`

</body>
</html>
`)
//line index.qtpl:44
}

//line index.qtpl:44
func WriteIndex(qq422016 qtio422016.Writer) {
	//line index.qtpl:44
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line index.qtpl:44
	StreamIndex(qw422016)
	//line index.qtpl:44
	qt422016.ReleaseWriter(qw422016)
//line index.qtpl:44
}

//line index.qtpl:44
func Index() string {
	//line index.qtpl:44
	qb422016 := qt422016.AcquireByteBuffer()
	//line index.qtpl:44
	WriteIndex(qb422016)
	//line index.qtpl:44
	qs422016 := string(qb422016.B)
	//line index.qtpl:44
	qt422016.ReleaseByteBuffer(qb422016)
	//line index.qtpl:44
	return qs422016
//line index.qtpl:44
}
